services:
  db:
    image: "postgres:13.2"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  pgdata:
